export const LANGUAGE_LABELS: Record<string, string> = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  it: "Italiano",
  pt: "Português",
  ru: "Русский",
  zh: "中文",
  ja: "日本語",
  ko: "한국어",
  ar: "العربية",
  hi: "हिन्दी",
  bn: "বাংলা",
  ur: "اردو",
  nl: "Nederlands",
  pl: "Polski",
  tr: "Türkçe",
  vi: "Tiếng Việt",
  id: "Bahasa Indonesia",
  th: "ไทย",
  ms: "Bahasa Melayu",
  fil: "Filipino",
  sv: "Svenska",
  da: "Dansk",
  no: "Norsk",
  fi: "Suomi",
  cs: "Čeština",
  hu: "Magyar",
  ro: "Română",
  el: "Ελληνικά",
  bg: "Български",
  hr: "Hrvatski",
  sk: "Slovenčina",
  sl: "Slovenščina",
  lt: "Lietuvių",
  lv: "Latviešu",
  et: "Eesti",
  uk: "Українська",
  sr: "Српски",
  he: "עברית",
  kn: "ಕನ್ನಡ",
  pa: "ਪੰਜਾਬੀ",
  mr: "मराठी",
  ml: "മലയാളം",
  ta: "தமிழ்",
  te: "తెలుగు",
  gu: "ગુજરાતી",
  as: "অসমীয়া",
  kok: "कोंकणी",
  ks: "کٲشُر",
  mni: "ꯃꯤꯇꯩ ꯂꯩꯕꯥꯔꯤ",
  si: "සිංහල",
  ne: "नेपाली"
} 