export const LANGUAGES = {
  all: '🌐',
  en: '🇺🇸',
  es: '🇪🇸',
  fr: '🇫🇷',
  de: '🇩🇪',
  it: '🇮🇹',
  pt: '🇵🇹',
  ru: '🇷🇺',
  zh: '🇨🇳',
  ja: '🇯🇵',
  ko: '🇰🇷',
  ar: '🇸🇦',
  hi: '🇮🇳',
  bn: '🇧🇩',
  ur: '🇵🇰',
  nl: '🇳🇱',
  pl: '🇵🇱',
  tr: '🇹🇷',
  vi: '🇻🇳',
  id: '🇮🇩',
  th: '🇹🇭',
  ms: '🇲🇾',
  fil: '🇵🇭',
  sv: '🇸🇪',
  da: '🇩🇰',
  no: '🇳🇴',
  fi: '🇫🇮',
  cs: '🇨🇿',
  hu: '🇭🇺',
  ro: '🇷🇴',
  el: '🇬🇷',
  bg: '🇧🇬',
  hr: '🇭🇷',
  sk: '🇸🇰',
  sl: '🇸🇮',
  lt: '🇱🇹',
  lv: '🇱🇻',
  et: '🇪🇪',
  uk: '🇺🇦',
  sr: '🇷🇸',
  he: '🇮🇱',
  kn: '🇮🇳',
  pa: '🇮🇳',
  mr: '🇮🇳',
  ml: '🇮🇳',
  ta: '🇮🇳',
  te: '🇮🇳',
  gu: '🇮🇳',
  as: '🇮🇳',
  kok: '🇮🇳',
  ks: '🇮🇳',
  mni: '🇮🇳',
  si: '🇱🇰',
  ne: '🇳🇵'
} as const

export type Language = keyof typeof LANGUAGES

export const LANGUAGE_DISPLAY_NAMES: Record<string, string> = {
  all: 'All Languages',
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  ru: 'Русский',
  zh: '中文',
  ja: '日本語',
  ko: '한국어',
  ar: 'العربية',
  hi: 'हिन्दी',
  bn: 'বাংলা',
  ur: 'اردو',
  nl: 'Nederlands',
  pl: 'Polski',
  tr: 'Türkçe',
  vi: 'Tiếng Việt',
  id: 'Bahasa Indonesia',
  th: 'ไทย',
  ms: 'Bahasa Melayu',
  fil: 'Filipino',
  sv: 'Svenska',
  da: 'Dansk',
  no: 'Norsk',
  fi: 'Suomi',
  cs: 'Čeština',
  hu: 'Magyar',
  ro: 'Română',
  el: 'Ελληνικά',
  bg: 'Български',
  hr: 'Hrvatski',
  sk: 'Slovenčina',
  sl: 'Slovenščina',
  lt: 'Lietuvių',
  lv: 'Latviešu',
  et: 'Eesti',
  uk: 'Українська',
  sr: 'Српски',
  he: 'עברית',
  kn: 'ಕನ್ನಡ',
  pa: 'ਪੰਜਾਬੀ',
  mr: 'मराठी',
  ml: 'മലയാളം',
  ta: 'தமிழ்',
  te: 'తెలుగు',
  gu: 'ગુજરાતી',
  as: 'অসমীয়া',
  kok: 'कोंकणी',
  ks: 'کٲشُر',
  mni: 'ꯃꯤꯇꯩ ꯂꯩꯕꯥꯔꯤ',
  si: 'සිංහල',
  ne: 'नेपाली'
}

export const LANGUAGE_MAPPING: Record<string, Language> = {
  'en': 'en',
  'es': 'es',
  'fr': 'fr',
  'de': 'de',
  'it': 'it',
  'pt': 'pt',
  'ru': 'ru',
  'zh': 'zh',
  'ja': 'ja',
  'ko': 'ko',
  'ar': 'ar',
  'hi': 'hi',
  'bn': 'bn',
  'ur': 'ur',
  'nl': 'nl',
  'pl': 'pl',
  'tr': 'tr',
  'vi': 'vi',
  'id': 'id',
  'th': 'th',
  'ms': 'ms',
  'fil': 'fil',
  'sv': 'sv',
  'da': 'da',
  'no': 'no',
  'fi': 'fi',
  'cs': 'cs',
  'hu': 'hu',
  'ro': 'ro',
  'el': 'el',
  'bg': 'bg',
  'hr': 'hr',
  'sk': 'sk',
  'sl': 'sl',
  'lt': 'lt',
  'lv': 'lv',
  'et': 'et',
  'uk': 'uk',
  'sr': 'sr',
  'he': 'he',
  'kn': 'kn',
  'pa': 'pa',
  'mr': 'mr',
  'ml': 'ml',
  'ta': 'ta',
  'te': 'te',
  'gu': 'gu',
  'as': 'as',
  'kok': 'kok',
  'ks': 'ks',
  'mni': 'mni',
  'si': 'si',
  'ne': 'ne'
} 